Repository FEX-Emu/FEX, pull requests merged in 2023-07, with the labels that each got.

#2740 Linux: Stop using faccessat2 for faccessat emulation
  Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
Labels: Ready For Review

#2738 Linux: Handle xattr syscalls with emulated paths.
  Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.h
  Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/FS.cpp
Labels: Ready For Review

#2741 FHU: Workaround libstdc++ version 13+ bug
  FEXHeaderUtils/FEXHeaderUtils/Filesystem.h
Labels: Ready For Review

#2739 Linux: Fixes hangs due to mutexes locked while fork happens.
  External/FEXCore/Source/Interface/Context/Context.h
  External/FEXCore/Source/Interface/Core/Core.cpp
  External/FEXCore/Source/Utils/Allocator.cpp
  External/FEXCore/Source/Utils/Allocator.h
  External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
  External/FEXCore/Source/Utils/Allocator/HostAllocator.h
  External/FEXCore/include/FEXCore/Core/Context.h
  External/FEXCore/include/FEXCore/Utils/DeferredSignalMutex.h
  FEXHeaderUtils/FEXHeaderUtils/ScopedSignalMask.h
  Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.h
  Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Thread.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/SyscallsSMCTracking.cpp
Labels: high priority, Ready For Review

#2743 FEXCore: Minor cleanup
  External/FEXCore/Source/Interface/Context/Context.cpp
  External/FEXCore/Source/Interface/Core/Core.cpp
  External/FEXCore/Source/Interface/Core/Core.h
Labels: Ready For Review

#2746 OpcodeDispatcher: Optimize MASKMOVDQU and MASKMOVQ
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Labels: Performance, Ready For Review

#2745 OpcodeDispatcher: Optimize GetPackedRFLAG
  External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
Labels: Ready For Review

#2748 unittests: Adds missing header
  unittests/Utilities/DeleteOldSHMRegions.cpp
Labels: Ready For Review

#2750 OpcodeDispatcher: Fixes bug with pcmpestri
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/ASM/FEX_bugs/pcmpestri_garbage_rcx.asm
Labels: bug, IR, Java bug, Ready For Review

#2749 OpcodeDispatcher: Optimize some shifts size masking
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  External/FEXCore/Source/Interface/IR/IR.json
  External/FEXCore/include/FEXCore/IR/IREmitter.h
  unittests/IR/Correctness/LeftShiftTruncate.ir
Labels: Ready For Review

#2756 OpcodeDispatcher: Optimize MOVSS to memory destination
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Labels: IR, Performance, Ready For Review

#2758 IR: Optimize vector TSO loadstore address calculation
  External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
Labels: IR, Performance, Ready For Review

#2757 OpcodeDispatcher: Optimize MOVSS to register
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Labels: IR, Performance, Ready For Review

#2759 OpcodeDispatcher: Remove spurious bfe with flag storing
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
Labels: IR, Performance, Ready For Review

#2742 FEXCore: Fixes WIN32 compiling again
  External/FEXCore/Source/Interface/Context/Context.h
  External/FEXCore/Source/Interface/Core/Core.cpp
  External/FEXCore/Source/Utils/Telemetry.cpp
  External/FEXCore/include/FEXCore/Core/Context.h
  External/FEXCore/include/FEXCore/Utils/DeferredSignalMutex.h
  External/FEXCore/include/FEXCore/Utils/Telemetry.h
  External/FEXCore/include/FEXCore/fextl/fmt.h
  FEXHeaderUtils/FEXHeaderUtils/SymlinkChecks.h
  Source/Common/CMakeLists.txt
  Source/Common/Config.cpp
Labels: Ready For Review

#2762 FEXRootFSFetcher: Make verification percent easier to read
  Source/Tools/FEXRootFSFetcher/XXFileHash.cpp
Labels: Ready For Review

#2764 FEXCore: Removes unused TLS variable
  External/FEXCore/Source/Interface/Core/Core.cpp
Labels: Ready For Review

#2766 OpcodeDispatcher: Optimize ADD/ADC OF flag packing
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
Labels: Performance

#2768 OpcodeDispatcher: Fix and optimize PF calculation
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  unittests/ASM/FEX_bugs/Test_JP.asm
Labels: bug, CPU emulation

#2747 Thunks: Fixes thunks in non-multiarch
  Data/ThunksDB.json
  FEXHeaderUtils/FEXHeaderUtils/Filesystem.h
  Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.h
Labels: Ready For Review

#2774 CMake: Fix pkg version extraction for xcb
  CMakeFiles/version_to_variables.cmake
  ThunkLibs/GuestLibs/CMakeLists.txt
  ThunkLibs/HostLibs/CMakeLists.txt
  ThunkLibs/libxcb/libxcb_interface.cpp
Labels: Ready For Review

#2782 OpcodeDispatcher: Minor optimization to FILD
  External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
  External/FEXCore/Source/Interface/Core/HostFeatures.cpp
  External/FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
  External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  External/FEXCore/Source/Interface/IR/IR.json
  External/FEXCore/include/FEXCore/Core/HostFeatures.h
  External/FEXCore/unittests/Emitter/ALU_Tests.cpp
Labels: Performance, JIT, AArch64 Host, Ready For Review

#2777 IR/Passes: Fixes DeadStoreElimination pass
  External/FEXCore/Source/Interface/IR/Passes/DeadStoreElimination.cpp
Labels: IR, Performance, Ready For Review

#2778 SignalDelegator: Moves last TLS variable to the frontend
  External/FEXCore/Source/Interface/Core/SignalDelegator.cpp
  External/FEXCore/include/FEXCore/Core/SignalDelegator.h
  Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.h
Labels: Ready For Review, llvm-mingw

#2779 OpcodeDispatcher: Optimize 32/64-bit SH{L,R}D with extr
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
Labels: Performance, JIT, Ready For Review

#2781 OpcodeDispatcher: Minor optimization to phminposuw
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Labels: Performance, JIT, Ready For Review

#2785 ArmEmitter: Support 32-bit bitmask moves
  External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
Labels: Performance, JIT, AArch64 Host, Ready For Review

#2791 Thunks/xcb: Fixes typo in version check.
  ThunkLibs/libxcb/libxcb_interface.cpp
Labels: Ready For Review

#2787 Arm64: Only clear icache for code
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
Labels: AArch64 Host, Ready For Review

#2786 OpcodeDispatcher: Another FCMov minor optimization
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
  External/FEXCore/include/FEXCore/Core/X86Enums.h
Labels: Performance, JIT, Ready For Review

#2788 FEXCore/Config: Adds support for enum mask configuration array
  External/FEXCore/Scripts/config_generator.py
  External/FEXCore/Source/Interface/Config/Config.cpp
  External/FEXCore/Source/Interface/Config/Config.json.in
  External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
  External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  External/FEXCore/include/FEXCore/Config/Config.h
  Source/Tools/FEXConfig/Main.cpp
Labels: Ready For Review

#2784 OpcodeDispatcher: Optimize 8/16-bit RCR
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
Labels: Performance, JIT, CPU emulation, Ready For Review

#2783 Arm64: Optimize {Load,Store}ContextIndexed address generation
  .github/workflows/ccpp.yml
  .github/workflows/glibc_fault.yml
  External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
  External/FEXCore/include/FEXCore/Utils/MathUtils.h
  External/FEXCore/unittests/APITests/CMakeLists.txt
  External/FEXCore/unittests/APITests/ILog2.cpp
  External/FEXCore/unittests/CMakeLists.txt
Labels: Performance, JIT, AArch64 Host, Ready For Review

#2795 Thunks: Remove weak symbol definitions
  ThunkLibs/include/common/Host.h
Labels: bug, Usability, Thunk bug, Ready For Review

#2803 ThunksDB: Adds X11 dependency to XCB
  Data/ThunksDB.json
Labels: Thunk bug, Ready For Review

#2763 Thunks/X11: Fixes variadic packing and callbacks.
  ThunkLibs/libX11/X11Common.h
  ThunkLibs/libX11/libX11_Guest.cpp
  ThunkLibs/libX11/libX11_Host.cpp
  ThunkLibs/libX11/libX11_interface.cpp
Labels: high priority, AArch64 Host, Thunk bug, Ready For Review

#2813 Arm64: Fixes LR corruption in 128-bit divides
  External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
Labels: JIT, AArch64 Host, Ready For Review

#2821 RCLSE: Rename `Node` to `ValueNode`
  External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
Labels: IR, Ready For Review

#2822 StructPackVerifier: Fixes missing cursorkind again
  Scripts/StructPackVerifier.py
Labels: Ready For Review

#2760 Arm64: Switch to using half barriers
  External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
  External/FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
  External/FEXCore/include/FEXCore/Utils/ArchHelpers/Arm64.h
Labels: Performance, AArch64 Host, Ready For Review

#2823 Mingw: Fixes compiling again
  External/FEXCore/unittests/CMakeLists.txt
  Source/Tools/FEXLoader/CMakeLists.txt
  Source/Tools/FEXLoader/WindowsDummyHandlers.cpp
  Source/Tools/FEXLoader/WindowsDummyHandlers.h
Labels: Ready For Review

#2830 FEXLinuxTests: Fixes race in smc-mt-2
  unittests/FEXLinuxTests/tests/smc/smc-mt-2.cpp
Labels: Ready For Review

#2833 FEXCore: Remove erroneous asserts in the project
  External/FEXCore/Scripts/json_ir_generator.py
  External/FEXCore/Source/Interface/Config/Config.cpp
  External/FEXCore/Source/Interface/Core/Frontend.cpp
  External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h
Labels: Ready For Review

#2835 ARMEmitter: Implement cmn alias
  External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
  External/FEXCore/unittests/Emitter/ALU_Tests.cpp
Labels: Ready For Review

#2842 Linux: Implement accept4 inside of socketcall
  Source/Tools/FEXLoader/LinuxSyscalls/x32/Socket.cpp
Labels: Ready For Review

#2843 Linux: Implement {recv,send}mmsg inside of socketcall
  Source/Tools/FEXLoader/LinuxSyscalls/x32/Socket.cpp
Labels: Ready For Review

#2839 OpcodeDispatcher: Fixes SHRD by immediate OF flag calculation
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  unittests/ASM/FEX_bugs/SHRD_OF.asm
Labels: Ready For Review

#2845 Thunks: Set bitness flags for 64-bit guests
  ThunkLibs/GuestLibs/CMakeLists.txt
Labels: Ready For Review

#2817 OpcodeDispatcher: Optimize PSAD* to use vuabdl{2,}
  External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  External/FEXCore/Source/Interface/IR/IR.json
Labels: IR, JIT, AArch64 Host, Ready For Review
