Repository FEX-Emu/FEX, pull requests merged in 2023-08, with the labels that each got.

#2829 Github: Adds mingw build test workflow
  .github/workflows/mingw_build.yml
Labels: Ready For Review

#2851 OpcodeDispatcher: Optimize CMPXCHG{8B,16B} final comparison
  External/FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
  External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
  External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  External/FEXCore/Source/Interface/IR/IR.json
  External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
  External/FEXCore/include/FEXCore/IR/IREmitter.h
Labels: JIT, Ready For Review

#2852 OpcodeDispatcher: Optimize phsubsw/phaddsw
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Labels: JIT, Ready For Review

#2856 CMake: Allow overriding linker
  .github/workflows/mingw_build.yml
  CMakeLists.txt
Labels: Ready For Review

#2858 X86Tables: Fixes CLZero destination address
  External/FEXCore/Source/Interface/Core/X86Tables/SecondaryModRMTables.cpp
  unittests/32Bit_ASM/SecondaryModRM/Reg_7_4_2.asm
Labels: Ready For Review

#2866 Arm64: Remove erroneous LoadConstant
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
Labels: JIT, AArch64 Host, Ready For Review

#2861 FEXCore: Fixes vector shifts by zero
  External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/ASM/FEX_bugs/VectorShift_zero.asm
  unittests/ASM/FEX_bugs/VectorShift_zero_256.asm
  unittests/ASM/FEX_bugs/VectorShift_zero_avx_128.asm
Labels: bug, IR, JIT, Ready For Review

#2862 ARM64: Optimize vector zeroing
  External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
Labels: AArch64 Host, Ready For Review

#2865 Arm64: Implement first SVE-128bit optimization
  External/FEXCore/Scripts/config_generator.py
  External/FEXCore/Source/Interface/Config/Config.json.in
  External/FEXCore/Source/Interface/Core/HostFeatures.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  External/FEXCore/include/FEXCore/Config/Config.h
  External/FEXCore/include/FEXCore/Core/HostFeatures.h
  External/FEXCore/include/FEXCore/Utils/EnumOperators.h
Labels: Performance, JIT, AArch64 Host, Ready For Review

#2863 Arm64: Adds stats to the disassembly
  External/FEXCore/Source/Interface/Config/Config.json.in
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
Labels: AArch64 Host, Ready For Review

#2868 IR: Adds Option to run the IRDumper with more configurations
  External/FEXCore/Source/CMakeLists.txt
  External/FEXCore/Source/Interface/Config/Config.json.in
  External/FEXCore/Source/Interface/Context/Context.h
  External/FEXCore/Source/Interface/Core/Core.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
  External/FEXCore/Source/Interface/IR/IR.json
  External/FEXCore/Source/Interface/IR/IRParser.cpp
  External/FEXCore/Source/Interface/IR/PassManager.cpp
  External/FEXCore/Source/Interface/IR/PassManager.h
  External/FEXCore/Source/Interface/IR/Passes.h
  External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp
  External/FEXCore/Source/Interface/IR/Passes/IRDumperPass.cpp
Labels: IR, Ready For Review

#2867 FEX: Create a CommonTools static library
  Source/Tools/CMakeLists.txt
  Source/Tools/CommonTools/CMakeLists.txt
  Source/Tools/CommonTools/DummyHandlers.cpp
  Source/Tools/CommonTools/DummyHandlers.h
  Source/Tools/FEXLoader/CMakeLists.txt
  Source/Tools/FEXLoader/TestHarnessRunner.cpp
Labels: Ready For Review

#2871 FEXCore: Fixes Arm64 stats disassembly
  External/FEXCore/Source/Interface/Core/Core.cpp
  External/FEXCore/Source/Interface/Core/Frontend.cpp
  External/FEXCore/Source/Interface/Core/Frontend.h
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
  External/FEXCore/Source/Interface/IR/IR.json
  External/FEXCore/Source/Interface/IR/IRDumper.cpp
  External/FEXCore/Source/Interface/IR/IRParser.cpp
  External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp
  unittests/IR/Basic/MemoryData.ir
  unittests/IR/Basic/Sbfe.ir
  unittests/IR/Basic/SetGPR.ir
  unittests/IR/Correctness/AddTruncate.ir
  unittests/IR/Correctness/FPRStoreTruncate.ir
  unittests/IR/Correctness/LeftShiftTruncate.ir
  unittests/IR/Correctness/SubTruncate.ir
Labels: AArch64 Host, Ready For Review

#2872 FEX: Adds instruction count CI
  .github/workflows/vixl_simulator.yml
  External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
  External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
  External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
  External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.h
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  External/FEXCore/include/FEXCore/Utils/File.h
  Scripts/InstructionCountParser.py
  Scripts/UpdateInstructionCountJson.py
  Source/Tools/CMakeLists.txt
  Source/Tools/CodeSizeValidation/CMakeLists.txt
  Source/Tools/CodeSizeValidation/Main.cpp
  unittests/CMakeLists.txt
  unittests/InstructionCountCI/CMakeLists.txt
  unittests/InstructionCountCI/SecondaryGroup.json
Labels: Ready For Review

#2879 FEXCore: Fixes bug with 32-bit adcx
  External/FEXCore/Source/Interface/Core/Frontend.cpp
  External/FEXCore/Source/Interface/Core/X86Tables/H0F38Tables.cpp
  unittests/ASM/FEX_bugs/adcx_size.asm
Labels: Ready For Review

#2877 InstructionCountCI: Adds three more instruction tables
  External/FEXCore/Source/Interface/Config/Config.json.in
  External/FEXCore/Source/Interface/Core/HostFeatures.cpp
  Scripts/InstructionCountParser.py
  Source/Tools/CodeSizeValidation/Main.cpp
  unittests/InstructionCountCI/DDD.json
  unittests/InstructionCountCI/H0F3A.json
  unittests/InstructionCountCI/SecondaryModRM.json
Labels: Ready For Review

#2883 InstCountCI: Adds H0F38 table
  unittests/InstructionCountCI/H0F38.json
Labels: Ready For Review

#2884 InstCountCI: Adds x87 table
  unittests/InstructionCountCI/x87.json
Labels: Ready For Review

#2885 InstCountCI: Adds VEX map1 tables
  unittests/InstructionCountCI/VEX_map1.json
Labels: Ready For Review

#2886 InstCountCI: Adds FEX map2 tables
  Scripts/InstructionCountParser.py
  unittests/InstructionCountCI/VEX_map2.json
Labels: Ready For Review

#2888 InstCountCI: Adds VEX map group tables
  unittests/InstructionCountCI/VEX_map_group.json
Labels: Ready For Review

#2887 InstCountCI: Adds VEX map3 tables
  External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
  Scripts/InstructionCountParser.py
  Source/Tools/CodeSizeValidation/Main.cpp
  unittests/InstructionCountCI/VEX_map3.json
Labels: Ready For Review

#2889 InstCountCI: Adds Primary group tables
  unittests/InstructionCountCI/PrimaryGroup.json
Labels: Ready For Review

#2892 Config: Minor changes
  External/FEXCore/Source/Interface/Config/Config.cpp
  External/FEXCore/Source/Interface/Config/Config.json.in
  External/FEXCore/Source/Interface/IR/PassManager.cpp
  Source/Tools/FEXLoader/TestHarnessRunner.cpp
Labels: Ready For Review

#2893 InstCountCI: Adds secondary tables
  External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
  Source/Tools/CodeSizeValidation/Main.cpp
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_32Bit.json
Labels: Ready For Review

#2894 InstCountCI: Adds secondary prefix tables
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_REP.json
  unittests/InstructionCountCI/Secondary_REPNE.json
Labels: Ready For Review

#2899 InstCountCI: Ensure output nasm name doesn't conflict
  Scripts/InstructionCountParser.py
Labels: Ready For Review

#2901 InstCountCI: Disables tests with unsupported configurations
  unittests/CMakeLists.txt
Labels: Ready For Review

#2903 InstCountCI: Adds RNG support
  Scripts/InstructionCountParser.py
  Source/Tools/CodeSizeValidation/Main.cpp
  unittests/InstructionCountCI/SecondaryGroup.json
Labels: Ready For Review

#2905 InstCountCI: Update tests from actual ARM64 device
  unittests/InstructionCountCI/SecondaryGroup.json
  unittests/InstructionCountCI/SecondaryModRM.json
  unittests/InstructionCountCI/VEX_map_group.json
  unittests/InstructionCountCI/x87.json
Labels: Ready For Review

#2907 FEXCore/IR: Fixes bug in IRDumper without specification
  External/FEXCore/Source/Interface/IR/PassManager.cpp
Labels: IR, Ready For Review

#2913 Filemanagement: Optimize GetSelf using a string_view
  External/FEXCore/include/FEXCore/Config/Config.h
  Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.h
Labels: Linux Guest, Performance, Ready For Review

#2909 Arm64: Optimize CacheLine{Clear,Clean}
  External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
  unittests/InstructionCountCI/SecondaryGroup.json
Labels: Performance, JIT, AArch64 Host, Ready For Review

#2911 Arm64: Stop abusing orr in LoadConstant
  External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
  unittests/InstructionCountCI/H0F38.json
  unittests/InstructionCountCI/H0F3A.json
  unittests/InstructionCountCI/Primary.json
  unittests/InstructionCountCI/PrimaryGroup.json
  unittests/InstructionCountCI/Primary_32Bit.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/SecondaryGroup.json
  unittests/InstructionCountCI/SecondaryModRM.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/VEX_map1.json
  unittests/InstructionCountCI/VEX_map2.json
  unittests/InstructionCountCI/VEX_map3.json
  unittests/InstructionCountCI/VEX_map_group.json
  unittests/InstructionCountCI/x87.json
Labels: Performance, AArch64 Host, Ready For Review

#2914 IR: Add VBroadcastFromMem opcode
  External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  External/FEXCore/Source/Interface/IR/IR.json
  unittests/InstructionCountCI/VEX_map2.json
Labels: IR, Performance, Ready For Review

#2916 Arm64Emitter: Ensure that 128-bit predicate is generated with SVE
  External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
Labels: bug, JIT, AArch64 Host

#2908 IR/ConstProp: Ensure that BFI with constant bitfields can optimize to Andn or Or
  FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
  unittests/InstructionCountCI/H0F38.json
  unittests/InstructionCountCI/Primary.json
  unittests/InstructionCountCI/Primary_32Bit.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/SecondaryGroup.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/VEX_map1.json
  unittests/InstructionCountCI/VEX_map2.json
  unittests/InstructionCountCI/VEX_map_group.json
Labels: IR, Performance, Ready For Review

#2928 Arm64Emitter: Stop saving and restoring platform register
  FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
Labels: AArch64 Host, Ready For Review

#2929 SignalDelegator: Allow getting the internal configuration
  FEXCore/include/FEXCore/Core/SignalDelegator.h
Labels: Ready For Review

#2912 OpcodeDispatcher: Minor optimization around clearing flags
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/SecondaryGroup.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_REP.json
  unittests/InstructionCountCI/VEX_map1.json
  unittests/InstructionCountCI/VEX_map2.json
  unittests/InstructionCountCI/VEX_map_group.json
Labels: IR, Performance, JIT, Ready For Review

#2930 OpcodeDispatcher: Implement support for push IR operation
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/IR/IR.json
  unittests/InstructionCountCI/Primary.json
  unittests/InstructionCountCI/PrimaryGroup.json
  unittests/InstructionCountCI/Primary_32Bit.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_32Bit.json
Labels: IR, Performance, Ready For Review

#2923 FEXCore: Adds telemetry around legacy segment register setting
  .github/workflows/instcountci.yml
  FEXCore/Source/Interface/Core/CPUBackend.cpp
  FEXCore/Source/Interface/Core/Interpreter/AtomicOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/x86_64/AtomicOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/IR/IR.json
  FEXCore/Source/Utils/Telemetry.cpp
  FEXCore/include/FEXCore/Core/CoreState.h
  FEXCore/include/FEXCore/Utils/Telemetry.h
Labels: Ready For Review

#2942 FEXInterpeter: Fixes compilation when telemetry is disabled
  Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
Labels: Ready For Review

#2943 IR: Implements support for wide scalar shifts
  FEXCore/Source/Interface/Core/Interpreter/InterpreterDefines.h
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  unittests/InstructionCountCI/Primary.json
  unittests/InstructionCountCI/PrimaryGroup.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_OpSize_SVE128.json
  unittests/InstructionCountCI/Secondary_SVE128.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: Performance, JIT, AArch64 Host, Ready For Review

#2947 OpcodeDispatcher: Optimize SSE/AVX pmaddubsw
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/H0F38.json
  unittests/InstructionCountCI/VEX_map2.json
Labels: Performance, Ready For Review

#2946 OpcodeDispatcher: Optimizes mpsadbw
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/H0F3A.json
  unittests/InstructionCountCI/VEX_map3.json
Labels: Performance, JIT, Ready For Review

#2931 Optimize PSIGN and VBSL
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  FEXCore/include/FEXCore/Core/CPUBackend.h
  unittests/InstructionCountCI/H0F38.json
  unittests/InstructionCountCI/Primary.json
  unittests/InstructionCountCI/PrimaryGroup.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/VEX_map1.json
  unittests/InstructionCountCI/VEX_map2.json
  unittests/InstructionCountCI/VEX_map3.json
  unittests/InstructionCountCI/x87.json
Labels: IR, Performance, JIT, AArch64 Host, Ready For Review

#2949 OpcodeDispatcher: Optimize phsub
  FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/H0F38.json
  unittests/InstructionCountCI/VEX_map2.json
Labels: Performance, JIT, Ready For Review

#2950 OpcodeDispatcher: Optimize pmaddwd
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: Performance, JIT, Ready For Review

#2954 OpcodeDispatcher: Optimize pmuludq
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/VEX_map1.json
  unittests/InstructionCountCI/VEX_map2.json
Labels: Performance, JIT, Ready For Review

#2956 OpcodeDispatcher: Optimize hsubp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_REPNE.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: Performance, JIT, Ready For Review

#2957 OpcodeDispatcher: Optimize PFNACC
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/DDD.json
Labels: Performance, JIT, Ready For Review

#2958 OpcodeDispatcher: Optimize phminposuw
  FEXCore/Source/Interface/Core/CPUBackend.cpp
  FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
  FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.h
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  FEXCore/Source/Interface/IR/IRDumper.cpp
  FEXCore/include/FEXCore/Core/CoreState.h
  FEXCore/include/FEXCore/IR/IR.h
  unittests/InstructionCountCI/H0F38.json
  unittests/InstructionCountCI/PrimaryGroup.json
  unittests/InstructionCountCI/VEX_map2.json
Labels: Performance, JIT, Ready For Review

#2959 X86Tables: Optimize MOVLPD stores
  FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
  unittests/InstructionCountCI/Secondary_OpSize.json
Labels: Performance, Ready For Review

#2964 InstCountCI: Fix some mislabeled instructions
  unittests/InstructionCountCI/Secondary_OpSize.json
Labels: Ready For Review

#2963 OpcodeDispatcher: Optimize MOVLP{S,D} loads
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
Labels: Performance, JIT, Ready For Review

#2967 OpcodeDispatcher: Optimize MOVHP{S,D}
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
Labels: Performance, JIT, Ready For Review

#2970 Arm64: Optimize VFMin/VFMax
  FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  unittests/InstructionCountCI/DDD.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: Performance, AArch64 Host, Ready For Review

#2972 OpcodeDispatcher: Optimizes scalar movd/movq
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: Performance, JIT, Ready For Review

#2984 OpcodeDispatcher: Use new IR ops for pack instructions
  FEXCore/Source/Interface/Core/Interpreter/InterpreterDefines.h
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/VEX_map1.json
  unittests/InstructionCountCI/VEX_map2.json
Labels: IR, Performance, JIT, Ready For Review

#2990 OpcodeDispatcher: Optimize PMULH{U,}W using new IR operations
  FEXCore/Source/Interface/Core/Interpreter/InterpreterDefines.h
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_OpSize_SVE128.json
  unittests/InstructionCountCI/Secondary_OpSize_SVE256.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: IR, Performance, JIT, Ready For Review

#2993 OpcodeDispatcher: Optimize AddSubP{S,D}
  FEXCore/Source/Interface/Core/CPUBackend.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IRDumper.cpp
  FEXCore/include/FEXCore/IR/IR.h
  unittests/InstructionCountCI/PrimaryGroup.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_REPNE.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: IR, Performance, Ready For Review

#2998 OpcodeDispatcher: Optimize addsubp{s,d} using fcadd
  FEXCore/Source/Interface/Config/Config.json.in
  FEXCore/Source/Interface/Core/HostFeatures.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterDefines.h
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  FEXCore/include/FEXCore/Core/HostFeatures.h
  Scripts/InstructionCountParser.py
  Source/Tools/CodeSizeValidation/Main.cpp
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_OpSize_FCMA.json
  unittests/InstructionCountCI/Secondary_REPNE.json
  unittests/InstructionCountCI/Secondary_REPNE_FCMA.json
  unittests/InstructionCountCI/VEX_map1.json
  unittests/InstructionCountCI/VEX_map1_FCMA.json
Labels: IR, Performance, JIT, Ready For Review

#3000 OpcodeDispatcher: Optimize MMX conversion operation
  FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/DDD.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
Labels: Performance, JIT, Ready For Review

#3001 OpcodeDispatcher: Optimize cvtps2pd
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: Performance, JIT, Ready For Review

#3004 OpcodeDispatcher: Generate more optimal code for scalar GPR converts
  FEXCore/Source/Interface/Core/Interpreter/ConversionOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/Secondary_REP.json
  unittests/InstructionCountCI/Secondary_REPNE.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: Performance, JIT, Ready For Review

#3005 OpcodeDispatcher: Optimize nontemporal moves
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
  unittests/InstructionCountCI/Secondary_REP.json
  unittests/InstructionCountCI/Secondary_REPNE.json
Labels: Performance, JIT, Ready For Review

#3006 OpcodeDispatcher: Optimizes movq
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/Secondary_REP.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: Performance, JIT, Ready For Review

#3008 OpcodeDispatcher: Optimize movddup from register
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/Secondary_REPNE.json
Labels: IR, Performance, JIT, Ready For Review

#3002 OpcodeDispatcher: Optimize 128-bit movmaskpd
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/ASM/OpSize/66_50.asm
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: Performance, JIT, Ready For Review

#3003 OpcodeDispatcher: Optimize PSHUF{LW, HW, D}!
  FEXCore/Source/Interface/Core/CPUBackend.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  FEXCore/include/FEXCore/Core/CoreState.h
  FEXCore/include/FEXCore/IR/IR.h
  unittests/InstructionCountCI/PrimaryGroup.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_REP.json
  unittests/InstructionCountCI/Secondary_REPNE.json
Labels: IR, Performance, JIT, Ready For Review

#3009 X8764: Ensure frndint uses host rounding mode
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
Labels: bug, JIT, Ready For Review

#3010 Linux: Call exit_group when application tries
  Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Thread.cpp
Labels: bug, Ready For Review

#2857 IR: Fixes RAValidation for 32-bit applications
  FEXCore/Source/Interface/IR/Passes/RAValidation.cpp
Labels: Ready For Review

#3015 InstCountCI: Test rorx at max mask size
  unittests/InstructionCountCI/VEX_map3.json
Labels: Ready For Review

#3014 IR: Convert all Move+Atomic+ALU ops from implicit to explicit size
  FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
  FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
  FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
  FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/IR/IR.json
  FEXCore/Source/Interface/IR/IRParser.cpp
  FEXCore/include/FEXCore/IR/IR.h
  FEXCore/include/FEXCore/IR/IREmitter.h
  unittests/IR/Basic/Sbfe.ir
  unittests/IR/Correctness/AddTruncate.ir
  unittests/IR/Correctness/LeftShiftTruncate.ir
  unittests/IR/Correctness/SubTruncate.ir
Labels: IR, Ready For Review

#3012 OpcodeDispatcher: Optimizes SSE movmaskps
  FEXCore/Source/Interface/Core/CPUBackend.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  FEXCore/include/FEXCore/IR/IR.h
  unittests/InstructionCountCI/PrimaryGroup.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_REP.json
  unittests/InstructionCountCI/Secondary_REPNE.json
  unittests/InstructionCountCI/Secondary_SVE128.json
  unittests/InstructionCountCI/VEX_map1.json
Labels: IR, Performance, JIT, Ready For Review

#3013 IR/Passes/RA: Enable SRA for 32-bit GPRs
  FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
  unittests/32Bit_ASM/FEX_bugs/adc.asm
Labels: Performance, JIT, Ready For Review

#3016 InstCountCI: Update for previous changes
  unittests/InstructionCountCI/H0F38.json
  unittests/InstructionCountCI/H0F3A.json
  unittests/InstructionCountCI/Primary.json
  unittests/InstructionCountCI/PrimaryGroup.json
  unittests/InstructionCountCI/Primary_32Bit.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/SecondaryGroup.json
  unittests/InstructionCountCI/Secondary_32Bit.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_REP.json
  unittests/InstructionCountCI/VEX_map1.json
  unittests/InstructionCountCI/VEX_map2.json
  unittests/InstructionCountCI/VEX_map3.json
  unittests/InstructionCountCI/VEX_map_group.json
  unittests/InstructionCountCI/x87.json
Labels: Ready For Review

#3021 IR: Removes implicit sized {Create,Extract}ElementPair
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3022 IR: Removes sext IR helper
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3023 IR: Removes implicit sized mul ops
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3024 IR: Removes implicit sized lshl
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
  FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3025 IR: Removes implicit sized lshr
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3026 IR: Removes implicit sized or
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
  FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3027 IR: Removes implicit sized andn
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3028 IR: Removes implicit sized xor
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3029 IR: Removes bfi from variable size
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3030 IR: Removes implicit sized sub
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3031 IR: Removes implicit sized and
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3033 IR: Removes implicit sized bfe
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
  FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3034 IR: Removes implicit sized add
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
  FEXCore/include/FEXCore/IR/IREmitter.h
Labels: IR, Ready For Review

#3036 IR: Adds IR::OpSize to IRDumper
  FEXCore/Source/Interface/IR/IRDumper.cpp
Labels: IR, Ready For Review

#3039 IR: Adds printer for OpSize
  FEXCore/include/FEXCore/IR/IR.h
Labels: Ready For Review

#3037 OpcodeDispatcher: Removes erroneous debug log
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
Labels: Ready For Review

#3040 Arm64: Optimize AESKeyGenAssist
  FEXCore/Source/Interface/Core/CPUBackend.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
  FEXCore/Source/Interface/IR/IR.json
  FEXCore/include/FEXCore/IR/IR.h
  unittests/InstructionCountCI/H0F3A.json
  unittests/InstructionCountCI/PrimaryGroup.json
  unittests/InstructionCountCI/Secondary.json
  unittests/InstructionCountCI/Secondary_OpSize.json
  unittests/InstructionCountCI/Secondary_REP.json
  unittests/InstructionCountCI/Secondary_REPNE.json
  unittests/InstructionCountCI/VEX_map3.json
Labels: IR, Ready For Review

#3041 FEXCore: Allows disabling telemetry at runtime
  .github/workflows/instcountci.yml
  FEXCore/Source/Interface/Config/Config.json.in
  FEXCore/Source/Interface/Context/Context.h
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Utils/Telemetry.cpp
  FEXCore/include/FEXCore/Core/CoreState.h
  FEXCore/include/FEXCore/Utils/Telemetry.h
  Source/Tools/CodeSizeValidation/Main.cpp
  unittests/InstructionCountCI/PrimaryGroup.json
Labels: Ready For Review

#3043 OpcodeDispatcher: Optimize BLENDV when xmm0 is one of the sources
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  unittests/InstructionCountCI/H0F38.json
Labels: IR, Ready For Review

#3044 Arm64: Optimize AES operations by caching a zero register
  FEXCore/Source/Interface/Core/CPUBackend.cpp
  FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
  FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
  FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
  FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  FEXCore/Source/Interface/IR/IR.json
  FEXCore/Source/Interface/IR/IRDumper.cpp
  FEXCore/include/FEXCore/Core/CoreState.h
  FEXCore/include/FEXCore/IR/IR.h
  unittests/InstructionCountCI/H0F38.json
  unittests/InstructionCountCI/H0F3A.json
  unittests/InstructionCountCI/VEX_map1.json
  unittests/InstructionCountCI/VEX_map2.json
  unittests/InstructionCountCI/VEX_map3.json
  unittests/InstructionCountCI/VEX_map_group.json
Labels: IR, Performance, JIT, Ready For Review

#3042 OpcodeDispatcher: Optimize calls with push
  FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
Labels: IR, JIT, Ready For Review
