Repository FEX-Emu/FEX, pull requests merged in 2023-06, with the labels that each got.

#2493 Implement support for deferred asynchronous signals
  External/FEXCore/Source/Interface/Context/Context.h
  External/FEXCore/Source/Interface/Core/Core.cpp
  External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
  External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
  External/FEXCore/Source/Interface/IR/AOTIR.cpp
  External/FEXCore/Source/Interface/IR/AOTIR.h
  External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
  External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
  External/FEXCore/Source/Utils/Allocator/HostAllocator.h
  External/FEXCore/include/FEXCore/Core/Context.h
  External/FEXCore/include/FEXCore/Core/CoreState.h
  External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
  External/FEXCore/include/FEXCore/HLE/SyscallHandler.h
  External/FEXCore/include/FEXCore/Utils/DeferredSignalMutex.h
  FEXHeaderUtils/FEXHeaderUtils/ScopedSignalMask.h
  Source/Tools/FEXLoader/ELFCodeLoader.h
  Source/Tools/FEXLoader/IRLoader.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.h
  Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Memory.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/SyscallsSMCTracking.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/x32/Memory.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/x32/Semaphore.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/x32/Syscalls.h
  Source/Tools/FEXLoader/LinuxSyscalls/x64/Memory.cpp
  Source/Tools/FEXLoader/LinuxSyscalls/x64/Syscalls.h
  Source/Tools/FEXLoader/VDSO_Emulation.cpp
  docs/DeferredSignals.md
Labels: Ready For Review

#2689 CPUID: Only enable BMI1 and BMI2 if AVX is supported
  External/FEXCore/Source/Interface/Core/CPUID.cpp
Labels: release-blocker, Regression, Ready For Review

#2699 X87: Super minor FCMOV optimization
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
Labels: IR, Ready For Review

#2701 OpcodeDispatcher: Optimize EFLAG unpacking
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
Labels: IR, Ready For Review

#2702 IRDumper: Fixes ssa number in arguments.
  External/FEXCore/Source/Interface/IR/IRDumper.cpp
Labels: IR, Ready For Review

#2703 OpcodeDispatcher: Optimize ADC/ADD OF flag calculation
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
  External/FEXCore/Source/Interface/IR/IR.json
Labels: IR, Performance, JIT, CPU emulation, Ready For Review

#2705 InstallFEX: Updates helper install script for Ubuntu 23.04
  Scripts/InstallFEX.py
Labels: Ready For Review

#2704 FEXRootFSFetcher: Support rolling release distros
  Source/Tools/FEXRootFSFetcher/Main.cpp
Labels: Ready For Review

#2706 FEXConfig: Removes Emulated CPU cores option
  Source/Tools/FEXConfig/Main.cpp
Labels: Ready For Review

#2714 x32/Thread: Fixes robust futex fetching
  Source/Tools/FEXLoader/LinuxSyscalls/x32/Thread.cpp
Labels: Ready For Review

#2715 Arm64: Fixes register pair conflict.
  External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
Labels: Ready For Review

#2723 IR: Move VPCMPESTRX REX handling to OpcodeDispatcher
  External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
  External/FEXCore/Source/Interface/IR/IR.json
Labels: IR, JIT

#2719 OpcodeDispatcher: Ensure MXCSR is saved/restored with FXSAVE/FXRSTOR
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Labels: bug, CPU emulation

#2722 JIT: Implement support for per-instruction RIP reconstruction
  External/FEXCore/Source/Interface/Core/Core.cpp
  External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
  External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
  External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
  External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
  External/FEXCore/include/FEXCore/Core/CPUBackend.h
Labels: JIT, CPU emulation, Ready For Review

#2735 Linux: Optimize CalculateHostKernelVersion
  Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
Labels: Performance, Ready For Review

#2729 Linux: Remove warning that isn't necessary anymore
  Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
Labels: Ready For Review

#2732 Context: Removes dead `AddVirtualMemoryMapping` function
  External/FEXCore/Source/Interface/Context/Context.cpp
  External/FEXCore/Source/Interface/Context/Context.h
  External/FEXCore/include/FEXCore/Core/Context.h
Labels: Ready For Review

#2725 Scripts: Disable using catchsegv if it doesn't exist
  Scripts/Threaded_Lockstep_Runner.py
  Scripts/testharness_runner.py
Labels: Ready For Review

#2731 FEXServerClient: Ensure server socket is created with SOCK_CLOEXEC
  Source/Common/FEXServerClient.cpp
Labels: Ready For Review
